# Generated by Django 4.2 on 2023-05-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='OldSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(choices=[('PS2', 'PS2'), ('PS ONE', 'PS ONE'), ('Wii', 'Wii'), ('PSP', 'PSP'), ('Game Boy', 'Game Boy'), ('Atari', 'Atari'), ('Nintendo DS', 'Nintendo DS'), ('Xbox Original', 'Xbox Original'), ('PC', 'PC')], max_length=13)),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_shop.userprofile')),
            ],
            options={
                'db_table': 'Old School',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(choices=[('PS3', 'PS3'), ('PS4', 'PS4'), ('PS5', 'PS5'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox Series X/S', 'Xbox Series X/S'), ('Nintendo Switch', 'Nintendo Switch')], max_length=15)),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_shop.userprofile')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
    ]
