# Generated by Django 4.1.7 on 2023-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0003_alter_game_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_shop.userprofile'),
        ),
    ]
