# Generated by Django 4.2 on 2023-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0004_alter_game_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='uploader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='game',
            table='Games',
        ),
        migrations.DeleteModel(
            name='OldSchool',
        ),
    ]
