# Generated by Django 4.2 on 2023-05-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0005_game_game_type_alter_game_uploader_alter_game_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_shop.userprofile'),
        ),
    ]
