# Generated by Django 4.2 on 2023-05-23 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0009_alter_game_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Inbox',
            },
        ),
    ]
