# Generated by Django 4.2 on 2023-05-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0012_alter_contactus_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactMsg',
        ),
    ]
