# Generated by Django 4.2 on 2023-05-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0013_rename_contactus_contactmsg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmsg',
            options={'verbose_name_plural': 'Mail'},
        ),
    ]
