# Generated by Django 4.2 on 2023-05-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0014_alter_contactmsg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmsg',
            name='title',
        ),
    ]
