# Generated by Django 4.2 on 2023-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0015_remove_contactmsg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmsg',
            name='body',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
