# Generated by Django 4.2 on 2023-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0016_contactmsg_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
