# Generated by Django 4.2 on 2023-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0018_alter_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
