# Generated by Django 4.2 on 2023-05-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0019_alter_userprofile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
