# Generated by Django 4.2 on 2023-05-27 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0020_remove_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only numbers from 0 to 9 are allowed.', regex='^[0-9]+$')]),
        ),
    ]
