# Generated by Django 4.1.7 on 2023-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0025_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/appImages/')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
    ]
