# Generated by Django 4.1.7 on 2023-06-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0026_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='game_img',
            new_name='background_img',
        ),
    ]
