# Generated by Django 4.1.7 on 2023-06-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0027_rename_game_img_images_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='background_img',
            field=models.ImageField(upload_to='images/appImages/'),
        ),
    ]
