# Generated by Django 4.1.7 on 2023-06-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0029_images_name_alter_images_background_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
