# Generated by Django 4.2 on 2023-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0031_alter_message_content_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
