# Generated by Django 4.2 on 2023-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0033_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='communication_way',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
