# Generated by Django 4.2 on 2023-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_shop', '0036_remove_message_communication_way_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
